import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme.provider";
import Redux_Provider from "@/provider/store-provider";
import Auth_Provider from "@/provider/auth-provider";
import Socket_Provider from "@/provider/socket-provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Redux_Provider>
            <Auth_Provider>
              <Socket_Provider>
                <Toaster />
                {children}
              </Socket_Provider>
            </Auth_Provider>
          </Redux_Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
