import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/provider/theme-provider'
import Redux_Provider from '@/provider/store-provider'
import Socket_Provider from '@/provider/socket-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Redux_Provider>
              <Socket_Provider>
                {children}
              </Socket_Provider>
            </Redux_Provider>
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
